# ==================================================
# Application
# ==================================================
spring.application.name=joysList
server.port=8081

# ==================================================
# PostgreSQL
# ==================================================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/joyslist_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:8459}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================================================
# JPA / Hibernate
# ==================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ==================================================
# Redis
# ==================================================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# ==================================================
# Kafka
# ==================================================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Consumer
spring.kafka.consumer.group-id=joyslist-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# JSON Deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Topic Management
spring.kafka.admin.auto-create=true
spring.kafka.admin.fail-fast=true

# ==================================================
# Security
# ==================================================
jwt.secret=${JWT_SECRET_KEY:QWERTYUIOPASDFGHJKLZXCVBNM1234567890abcdefABCDEFGH}

# ==================================================
# Seeded Admin
# ==================================================
app.admin.email=admin@joyslist.com
app.admin.username=admin

# ==================================================
# Logging
# ==================================================
logging.level.root=INFO
logging.level.com.tpdev.joysList=INFO
logging.level.org.springframework.security=DEBUG