# App Info
spring.application.name=joysList

# PostgreSQL DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/joyslist_db
spring.datasource.username=postgres
spring.datasource.password=8459
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA /Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT secret key
jwt.secret=QW5vdGhlclZlcnlTdXBlclNlY3JldEtleUZvckpXVFNpZ25pbmc=