package com.tpdev.joysList.entity.enums;

public enum CommunityType {
    ACTIVITY_PARTNERS, ARTISTS, CHILDCARE, GENERAL, GROUPS, LOCAL_NEWS_AND_VIEWS, LOST_AND_FOUND,
    MISSED_CONNECTIONS, MUSICIANS, PETS, POLITICS, RANTS_AND_RAVES, RIDESHARE, VOLUNTEERS
}
