package com.tpdev.joysList.entity.enums;

public enum EventType {
    FREE, FOOD_OR_DRINK, LITERARY, CHARITABLE, DANCE, SUSTAINABILITY, SINGLES, FITNESS_OR_HEALTH, COMPETITION,
    SALE, TECH, OUTDOOR, KID_FRIENDLY, MUSIC, CAREER, ART_OR_FILM, FEST_OR_FAIR
}
