package com.tpdev.joysList.entity.enums;

public enum JobType {
    TRANSPORTATION, GENERAL_LABOR, SKILLED_TRADES_OR_ARTISAN, SALES, FOOD_BEVERAGE_HOSPITALITY, CUSTOMER_SERVICE,
    ET_CETERA, ADMIN_OR_OFFICE, EDUCATION_OR_TEACHING, RETAIL_OR_WHOLESALE, ACCOUNTING_OR_FINANCE, HEALTHCARE,
    BUSINESS_OR_MANAGEMENT, MANUFACTURING, MARKETING_OR_ADVERTISEMENT, REAL_ESTATE, SALON_SPA_FITNESS, SCIENCE_BIOTECH,
    SECURITY, TV_FILM_VIDEO_RADIO, LEGAL_PARALEGAL, SYSTEMS_NETWORKING, WRITING_EDITING
}
