package com.tpdev.joysList.entity.enums;

public enum ServiceType {
    AUTOMOTIVE, BEAUTY, CELL_PHONE_OR_MOBILE, COMPUTER, CYCLE, EVENT, FARM_AND_GARDEN, FINANCIAL, HEALTH_AND_WELLNESS,
    HOUSEHOLD, LABOR_AND_MOVING, LEGAL, LESSONS_AND_TUTORING, MARINE, PET, REAL_ESTATE, SKILLED_TRADE, SMALL_BIZ_ADS,
    TRAVEL_OR_VACATION, WRITE_OR_EDIT_OR_TRANSLATION
}
